version: "3.1"
services: 
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:      
      MONGO_INITDB_DATABASE: HeensOrdering
    volumes: 
      - heens_data:/var/lib/mysql  
  # web:
  #   build: .
  #   command: npm start
  #   volumes: 
  #     - .:/usr/app/      
  #   ports: 
  #     - "49160:3000"
  #   depends_on: 
  #     - mongo-db
volumes: 
  heens_data: