version: "3.1"
services: 
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:      
      MONGO_INITDB_DATABASE: HeensOrdering
    volumes: 
      - heens_data:/var/lib/mysql  
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: npm start
  #   volumes:
  #     - .:/usr/app/
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes: 
      - .:/usr/app/
    ports: 
      - "3000:5000"
    depends_on: 
      - mongodb
volumes: 
  heens_data:
