version: "3.1"
services: 
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:      
      MONGO_INITDB_DATABASE: HeensOrdering
    volumes: 
      - heens_data:/var/lib/mysql  
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes: 
      - .:/usr/app/
    ports: 
      - "8080:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/db_heens
      NODE_ENV: production
      SECRET_KEY: th15isMYs3cr3tk3y


    depends_on: 
      - mongodb
volumes: 
  heens_data:
