export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';

// take order actions
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE';
export const SELECT_MENU_ITEM = 'SELET_MENU_ITEM';
export const SELECT_MENU_OPTION = 'SELECT_MENU_OPTION';
export const CONFIRM_MENU_ITEM = 'SELECT_MENU_ITEM';
export const CANCEL_MENU_ITEM = 'CANCEL_MENU_ITEM';
export const SAVE_ORDER = 'SAVE_ORER';
export const SAVE_ORDER_REQUEST = 'SAVE_ORDER_REQUEST';
export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_ERROR = 'SAVE_ORDER_ERROR';

// orders actions
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_ERROR = 'UPDATE_ORDER_STATUS_ERROR';


export const OPEN_ORDER_MODAL = 'OPEN_ORDER_MODAL';
export const CLOSE_ORDER_MODAL = 'CLOSE_ORDER_MODAL';
export const ORDER_SELECT_CATEGORY = 'ORDER_SELECT_CATEGORY';
export const ORDER_SELECT_MENU = 'ORDER_SELECT_MENU';
export const ORDER_UPDATE_TOTAL = 'ORDER_UPDATE_TOTAL';
export const ORDER_MENU_RESET = 'ORDER_MENU_RESET';
export const ORDER_ITEM_SELECTED = 'ORDER_ITEM_SELECTED';
