export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";

export const FETCHING_CUSTOMER = "FETCHING_CUSTOMERS";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMER_ERROR = "FETCH_CUSTOMERS_ERROR";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMERS";
