export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";

export const FETCHING_CUSTOMER = "FETCHING_CUSTOMERS";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMER_ERROR = "FETCH_CUSTOMERS_ERROR";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMERS";

export const CUSTOMER_CREATE_REQUEST = "CUSTOMER_CREATE_REQUEST";
export const CUSTOMER_CREATE_SUCCESS = "CUSTOMER_CREATE_SUCCESS";
export const CUSTOMER_CREATE_ERROR = "CUSTOMER_CREATE_ERROR";

export const CUSTOMER_GET_REQUEST = "CUSTOMER_GET_REQUEST";
export const CUSTOMER_GET_SUCCESS = "CUSTOMER_GET_SUCCESS";
export const CUSTOMER_GET_ERROR = "CUSTOMER_GET_ERROR";

export const CUSTOMER_UPDATE_REQUEST = "CUSTOMER_UPDATE_REQUEST";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_ERROR = "CUSTOMER_UPDATE_ERROR";

export const CATEGORY_FETCH_REQUEST = "CATEGORY_FETCH_REQUEST";
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS";
export const CATEGORY_FETCH_ERROR = "CATEGORY_FETCH_ERROR";

export const CATEGORY_GET_REQUEST = "CATEGORY_GET_REQUEST";
export const CATEGORY_GET_SUCCESS = "CATEGORY_GET_SUCCESS";
export const CATEGORY_GET_ERROR = "CATEGORY_GET_ERROR";

export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_ERROR = "CATEGORY_CREATE_ERROR";

export const CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_ERROR = "CATEGORY_UPDATE_ERROR";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_ERRROR = "CATEGORY_DELETE_ERROR";

export const MENU_FETCH_REQUEST = "MENU_FETCH_REQUEST";
export const MENU_FETCH_SUCCESS = "MENU_FETCH_SUCCESS";
export const MENU_FETCH_ERROR = "MENU_FETCH_ERROR";

export const MENU_GET_REQUEST = "MENU_GET_REQUEST";
export const MENU_GET_SUCCESS = "MENU_GET_SUCCESS";
export const MENU_GET_ERROR = "MENU_GET_ERRROR";

export const MENU_CREATE_REQUEST = "MENU_CREATE_REQUEST";
export const MENU_CREATE_SUCCESS = "MENU_CREATE_SUCCESS";
export const MENU_CREATE_ERROR = "MENU_CREATE_ERROR";

export const MENU_UPDATE_REQUEST = "MENU_UPDATE_REQUEST";
export const MENU_UPDATE_SUCCESS = "MENU_UPDATE_SUCCESS";
export const MENU_UPDATE_ERROR = "MENU_UPDATE_ERROR";

export const MENU_DELETE_REQUEST = "MENU_DELETE_REQUEST";
export const MENU_DELETE_SUCCESS = "MENU_DELETE_SUCCESS";
export const MENU_DELETE_ERROR = "MENU_DELETE_ERROR";

export const MENU_OPTION_ADD_REQUEST = "MENU_OPTION_ADD_REQUEST";
export const MENU_OPTION_ADD_SUCCESS = "MENU_OPTION_ADD_SUCCESS";
export const MENU_OPTION_ADD_ERROR = "MENU_OPTION_ADD_ERROR";

export const MENU_OPTION_DELETE_REQUEST = "MENU_OPTION_DELETE_REQUEST";
export const MENU_OPTION_DELETE_SUCCESS = "MENU_OPTION_DELETE_SUCCESS";
export const MENU_OPTION_DELETE_ERROR = "MENU_OPTION_DELETE_ERROR";
